add_newline = false

format = "$conda$directory$git_branch$git_status$character"

[conda]
format = "[$environment](dimmed green) "

[character]
format = "[❯](purple) "

[directory]
format = "[$path](dimmed blue) "
truncation_length = 1
truncation_symbol = "…/"

[git_branch]
format = "[$symbol$branch]($style) "
style = "dimmed red"
truncation_length = 8
truncation_symbol = ""

[git_status]
ahead = "⇡${count}"
behind = "⇣${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
style = "red"

[package]
disabled = true
